### ISSUE TITLE
Broken build against TPM2-TSS

### ISSUE THREAD

**Issue by rtkypoeluev** [WindRiver-OpenSourceLabs/cryptfs-tpm2#9]
The latest master version doesn't compile against either:
- https://github.com/intel/tpm2-tss/tree/1.x
- https://github.com/intel/tpm2-tss/tree/master

It would be good to update 
- https://github.com/WindRiver-OpenSourceLabs/cryptfs-tpm2/blob/master/README
to indicate a new compatible version of TPM2.0-TSS.

Thanks

**Comment by jiazhang0** [comment]
@rtkypoeluev Thanks for reporting this issue. I have reverted the patch adopt to a previous revision of the master branch of tpm2-tss. Now cryptfs-tpm2 is working well with the stable tpm2-tss 1.3.0.
